### ISSUE TITLE
Path separator mismatch on Windows

### ISSUE THREAD

**Issue by pawamoy** [oprypin/mkdocs-gen-files#3]
Hello @oprypin 🙂 
Still enjoying gen-files a lot!

I've just encountered the following issue on Windows (sorry, work...): gen-files warns me about files not existing.
It seems it's just a mismatch with path separators using backslashes on one side vs. forward slashes on the other:

```python
self._edit_paths: {
    'reference/package/index.md': 'src\\package\\__init__.py',
    ...
}
# while
page.file.src_path: 'reference\\package\\index.md'
```

...so this condition is always false:

https://github.com/oprypin/mkdocs-gen-files/blob/baf5a5e2ef0490fb2f9d2962c4edda66675a0a7d/mkdocs_gen_files/plugin.py#L44

I see that you are normalizing the path here:

https://github.com/oprypin/mkdocs-gen-files/blob/baf5a5e2ef0490fb2f9d2962c4edda66675a0a7d/mkdocs_gen_files/editor.py#L70

Maybe separators should not be replaced, or maybe the later comparison should wrap them in `Path` again or something.

What do you think?

**Comment by oprypin** [comment]
Hm I'm not sure if this is a bug. The exact right-hand values of `_edit_paths` are never being decided by mkdocs-gen-files, it's always the user of the plugin. Additionally, mkdocs-gen-files never calls `File.src_path`. So you must have done that.

The fact that `src_path` has backslashes in MkDocs itself is unfortunate, but, as I said, not strictly relevant here.

`edit_paths` are URL fragments rather than file path fragments. So it wouldn't necessarily be correct to try to replace backslashes. It only expects slashes.

Could you confirm or deny whether I understood your situation correctly? Or am I wrong that it was you who used `File.src_path` directly?

Just let me know and I'll be glad to consider this as a bug in case I am wrong :)

**Comment by oprypin** [comment]
Agh my comment is completely wrong, sorry. I'll delete it :D

**Comment by oprypin** [comment]
You're right, *editor.py* consistently normalizes paths while *plugin.py* doesn't normalize them. I'll fix that.

https://github.com/oprypin/mkdocs-gen-files/blob/baf5a5e2ef0490fb2f9d2962c4edda66675a0a7d/mkdocs_gen_files/plugin.py#L44-L45

**Comment by oprypin** [comment]
Check out #4

**Comment by pawamoy** [comment]
Thanks for the quick fix!
