### ISSUE TITLE
Add py.typed to distribution

### ISSUE THREAD

**Issue by johnthagen** [oprypin/mkdocs-gen-files#6]
See: https://www.python.org/dev/peps/pep-0561/

For `mypy` users to get type checking when coding against this library, a `py.typed` file should be vendored with the distribution.

For Poetry, see: https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/

**Comment by oprypin** [comment]
This project is typed. That should be obvious without boilerplate.

I am not willing to declare that this project is typed according to mypy, because, well, generally speaking it's not (not validated against it, anyway), and also I pretty much think mypy is doing everything wrong and I am very sad that good alternatives to it can't become popular.
